### PR TITLE
Included patch to enable --start-in-tray argv

### PR DESCRIPTION
**Pull request by trustlix**
I use awesome wm and the option to start deezer minimized on the tray is a must. I've created a simple patch to allow that.
Hopefully it's useful to other people.
Cheers!

### CODE REVIEW

**Comment by SibrenVasse** [comment]
Thank you for submitting a pull request!
I have tested you changes, but I can't seem to get it to work. When I start deezer like this:
```
deezer --start-in-tray
```
I still get a window on start. It looks like ready-to-show isn't even firing. Am I using it wrong? I use sway.

**Comment by trustlix** [comment]
> Thank you for submitting a pull request!
> I have tested you changes, but I can't seem to get it to work. When I start deezer like this:
> 
> ```
> deezer --start-in-tray
> ```
> 
> I still get a window on start. It looks like ready-to-show isn't even firing. Am I using it wrong? I use sway.

My setup here is X11 + compton + awesomewm. I'm running with `--start-in-tray` and it's working :(
Can you try to debug it to ensure ready-to-show is being fired and the code inside the new `if` statement is being executed?

**Comment by SibrenVasse** [comment]
I've tested [this patch](https://github.com/SibrenVasse/deezer/files/6733538/patch.txt) on X11 (xfce4 with picom), with the following result:

```
~ deezer --start-in-tray |& grep DEBUG:
DEBUG: ready-to-show fired
DEBUG: argv condition false
DEBUG: argv: /usr/lib/electron/electron,/usr/share/deezer/app.asar,--start-in-tray
```

**Comment by trustlix** [comment]
> I've tested [this patch](https://github.com/SibrenVasse/deezer/files/6733538/patch.txt) on X11 (xfce4 with picom), with the following result:
> 
> ```
> ~ deezer --start-in-tray |& grep DEBUG:
> DEBUG: ready-to-show fired
> DEBUG: argv condition false
> DEBUG: argv: /usr/lib/electron/electron,/usr/share/deezer/app.asar,--start-in-tray
> ```

This is the expected behavior and it should not show the main window since the `this.window.show()` call was skipped.

**Comment by SibrenVasse** [comment]
Yes I know, but it does show:
123942780-c26cca80-d99b-11eb-93f0-aba00f2f7a54

**Comment by trustlix** [comment]
> Yes I know, but it still shows the main window on startup:
> 123942780-c26cca80-d99b-11eb-93f0-aba00f2f7a54

I see. Unfortunately I can't replicate this behavior here.
I'll close the PR for now... better to not include the patch given this scenario.
Thanks

**Comment by SibrenVasse** [comment]
If I add a `this.window.hide()` call to your patch it also works on my system. Can you verify it also works for you? 
[patch](https://github.com/SibrenVasse/deezer/files/6776082/patch.txt)

**Comment by SibrenVasse** [comment]
The cli option has been included in v5.30.20.

**Pull request closed without merging**
